# Generated by Django 4.0.1 on 2022-01-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_birth_date_profile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='courses_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='courses_joined',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='questions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
